### ISSUE TITLE
Login does not work anymore

### ISSUE THREAD

**Issue by Treppenhouse** [marcusbuffett/chessmadra-frontend#13]
When I am going to https://chessmadra.com/login, enter my E-Mail Address and click on the "Login" Button of the E-Mail that arrives, it just sends me to an empty black page.

The Link looks something like this: https://chessmadra.com/authenticate?t=abc123

**Comment by marcusbuffett** [comment]
Ah good catch, did some large changes around routing and didn't think to check the auth flow, this is fixed now
