### ISSUE TITLE
Wrong symbol for dubious moves

### ISSUE THREAD

**Issue by alexandru-duca** [marcusbuffett/chessmadra-frontend#14]
As of right no, the opening builder annotates possible moves in four different ways:

- No symbol
- The gray symbol "!?"
- The yellow symbol "?"
- The red symbol "??"

![Screenshot from 2022-11-08 20-57-46](https://user-images.githubusercontent.com/107179714/200663208-5ffd5029-ccc6-4a90-aedd-a581c56cd214.png)

The symbol "!?" traditionally means "interesting move", but I am assuming you meant to use the symbol "?!" for "dubious move". You can find more information about the most common symbols on [Wikipedia](https://en.wikipedia.org/wiki/Chess_annotation_symbols#Evaluation_symbols). Lichess also offers a table with the most common ones:

![Screenshot from 2022-11-08 21-13-37](https://user-images.githubusercontent.com/107179714/200665787-7ff895a9-66f5-42d0-92f0-e348c221c365.png)

Additionally, Lichess colors the symbol "?!" in a light blue. Therefore, I suggest changing the gray symbol "!?" into the light blue symbol "?!".

**Comment by marcusbuffett** [comment]
Ah good catch! I think I'm going to keep it gray, since these pop up a lot and the blue just seemed a bit too attention-grabbing, but I have updated the symbol, and it's deploying now. Thanks!
