### ISSUE TITLE
Lost repertoires after new login

### ISSUE THREAD

**Issue by lexnederbragt** [marcusbuffett/chessmadra-frontend#18]
Thanks for Chessmadra! I enjoyed building a repertoire and memorizing it using the site. After a period of non-activity I had to sign in again. After following the login link I requested I got back in, but both my repertoires are now empty. 

Is there a way to get my repertoires back?

**Comment by alexandru-duca** [comment]
This also happend to me and I don't think that your reportoire can be recovered. I recommend always exporting your repertoire after working on it. This way, you can always import it back if it ever disappears again.

**Comment by marcusbuffett** [comment]
Yeah unfortunately a lot of repertoires got deleted by one incident a few months ago. No way to get them back :/ Daily database backups are one of my top priorities, but exporting every now and then is a good idea for now
